service: serverless-books-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: books/create.create
    events:
      - http:
          path: book/add
          method: post
          cors: true

  list:
    handler: books/list.list
    events:
      - http:
          path: books
          method: get
          cors: true

  get:
    handler: books/get.get
    events:
      - http:
          path: book/{uuid}
          method: get
          cors: true

  update:
    handler: books/update.update
    events:
      - http:
          path: book/{uuid}/update
          method: post
          cors: true

  delete:
    handler: books/delete.delete
    events:
      - http:
          path: book/{uuid}/delete
          method: post
          cors: true

resources:
  Resources:
    BooksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
